### ISSUE TITLE
Invalid Discord Invite

### ISSUE THREAD

**Issue by checkraisefold** [KunoichiZ/acnl-modding-info#187]
What it says on the tin. The Discord invite everywhere is invalid.

**Comment by nel-syv** [comment]
Is there any other way to get in touch? The README suggests to DM  `AinoMinako#7220`, but that account isn't accepting friend requests from strangers, so nobody who doesn't already share a server with them can start a DM.

**Comment by KunoichiZ** [comment]
@nel-syv Yeah the server was nuked and there aren't plans to make a new server. Sorry.
