### ISSUE TITLE
Discord Link is Invalid

### ISSUE THREAD

**Issue by austjones19** [KunoichiZ/acnl-modding-info#358]
**Describe the bug**
All links I've found to the Discord say the invite is invalid

**To Reproduce**
1. Go to (https://discord.com/invite/EZSxqRr)
2. See Error

**Expected behavior**
I expected to join the discord server so I am able to ask questions

**Screenshots**
![image](https://github.com/user-attachments/assets/a1b49db2-a669-4b8f-8535-157d97a20459)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 126.0.6478.63 (Official Build) (64-bit)

**Additional context**
I am trying to get insight on how to install from scratch on O3DS with Luma. I don't have an NTR build.

**Comment by KunoichiZ** [comment]
The discord server was shut down by Discord themselves and a new one has not been made. See #187.
