### ISSUE TITLE
On the releases page Beta 2 is labelled Beta 1

### ISSUE THREAD

**Issue by AmyMialee** [KunoichiZ/acnl-modding-info#88]
**Describe the bug**
On the releases page Beta 2 is labelled Beta 1

**To Reproduce**
Visit releases page

**Expected behaviour**
Beta 2 to be labelled Beta 2

**Screenshots**
![image](https://user-images.githubusercontent.com/10999535/76645710-7224eb80-6551-11ea-98b6-cc90de4331ad.png)

**Comment by KunoichiZ** [comment]
Fixed.
